### ISSUE TITLE
Issue with MonadBaseControl instance

### ISSUE THREAD

**Issue by sol** [scotty-web/scotty#110]
Throwing exception with `Control.Exception.Lifted.throwIO` does not result in a `500`.  The server will close the connection instead.  Here is a test case that reproduces the issue:

``` haskell
withApp (Scotty.get "/" $ EL.throwIO E.DivideByZero) $ do
  it "returns 500 on exceptions" $ do
    get "/" `shouldRespondWith` "<h1>500 Internal Server Error</h1>divide by zero" {matchStatus = 500}
```

**Comment by fumieval** [comment]
Use of MonadBaseControl in non-reader monad often results in strange behaviour. Perhaps we could reimplement ActionM using [the ReaderT pattern](https://www.fpcomplete.com/blog/2017/06/readert-design-pattern/) so that exceptions are handled more predictably.

**Comment by sebastian-philipp** [comment]
wow, this thing is active again?

**Comment by fumieval** [comment]
I'm one of scotty's new maintainers :)
