### ISSUE TITLE
is it possible that the function 'request' starts consuming the body?

### ISSUE THREAD

**Issue by KasperJanssens** [scotty-web/scotty#146]
I would like to pass the underlying request to the wai-conduit function sourceRequestBody (https://hackage.haskell.org/package/wai-conduit-3.0.0.2/docs/Network-Wai-Conduit.html). However, if I do this, the source seems to be empty. Further investigation showed that asking 'requestBody' (the wai function) from the request I get by launching the scotty function 'request' returns an empty bytestring. 
If I use the 'body' function from scotty I do seem to get the body, so I don't think there's anything wrong with my request. If I create a source immediately through 'yield' it also seems to work.

The only hypothesis I have is that performing 'request' already eats up a chunk of the body, and there's nothing left for the source anymore (small body in my test, so complete body eaten).

**Comment by xich** [comment]
Yes, this is a known issue that we are fixing.

The problem is that Scotty pre-reads the entire request body into memory at route matching time. (Which is obviously bad.)

The repo version should already fix this, but I haven't released a version that does yet. I will once I've done some more cleanup.

So perhaps try cloning this repo and installing from it? I'd love to hear if anything doesn't work before I release.

**Comment by KasperJanssens** [comment]
Okay, after some fiddling around I got my project using your git tip and that seems to functionally work indeed, passing the request to sourceRequestBody does something sane this time :-).

Could you tell me how the 'body' is now treated? I'll be be using this for potentially very big bodies (GB range, passing those in a source to somewhere else, as you can see), so I'm mainly looking for stuff that might become problematic (such as reading in the complete body, especially at route matching time ;-)).

**Comment by xich** [comment]
The new setup will only read the whole body into memory if you call the `body` method. You can get the underlying `requestBody` (from Network.Wai) for streaming needs:

```haskell
chunk <- liftIO requestBody =<< request
```

There is a slight complication regarding `param` (if you try to stream a body with form encoded params, and read one of the params before streaming the body), so the cleanup I'm doing is to let Scotty properly tell you when that is happening. It should be a rare case, and I as far as I know would always be a mistake anyway.

**Comment by KasperJanssens** [comment]
Okay, last but not least, by when do you think you can do a release? I will likely build from source and insert into our local hackage at work for now, but hackage is very annoying when you want to remove something from it, so I'm not going to name it 0.9.1 but something else, most likely. Unless you plan on releasing really soon, then I don't have to go through that stuff ;-)
