### ISSUE TITLE
Away

### ISSUE THREAD

**Issue by xich** [scotty-web/scotty#159]
I know there are people waiting on pull requests and releases, but I'm end stage of my dissertation writing and simply don't have time to think about Scotty. I likely won't have time until May.

Are there any must haves waiting in Pull Request purgatory? Please speak up!

I'd like to merge in what is absolutely necessary and do a quick release, but don't have the cycles to review everything that has accumulated while I've been writing. :-(

**Comment by xenog** [comment]
How did that dissertation go? Did you finish it already?

**Comment by thomasjm** [comment]
Question, does this project have a maintainer at the moment? There are a lot of open issues and pull requests (including one of my own) and I'm wondering if I should consider this project abandoned.

CC @RyanGlScott

**Comment by RyanGlScott** [comment]
I've been keeping the project in "maintenance mode" for a while—that is, keeping it building when new versions of GHC are released, merging PRs that fix very minor issues and/or typos, etc. That being said, I'm far from an expert on webdev stuff, so I really don't feel qualified enough to make judgments on PRs that add new functionality or make breaking changes.

I agree that we should find someone who can serve as a proper maintainer and has the necessary expertise to discern which new features should be added (and which shouldn't be added). I haven't heard from @xich in a while, so it's unclear to me if he plans to return to that role at some point. I'll try contacting him to see if something can be arranged.

**Comment by sordina** [comment]
@RyanGlScott what's the status of this issue? Is someone heading up future development of Scotty? I use this framework very often, so I'd love to know that it has a plan for the future. If the role is vacant I'd be interested in helping!

**Comment by xich** [comment]
https://github.com/scotty-web/scotty/issues/234
