### ISSUE TITLE
OPTIONS method

### ISSUE THREAD

**Issue by adarqui** [scotty-web/scotty#165]
Hi everyone,

Just wondering when this copy of scotty-0.9.1 will be available on hackage? The current version on hackage doesn't have support for "options"; but the github 0.9.1 version does.

I'm using cabal sandbox add-source in the meantime.

Thanks!

**Comment by xich** [comment]
Apologies, I'll hopefully get back around to Scotty next week sometime. Trying to finish up with school. :-)

**Comment by adarqui** [comment]
Ah np. Sorry, just noticed the "Away Please Read!" issue. No rush. I'm good with sandbox's "add-source".

Thanks for the response!
