### ISSUE TITLE
Does scotty support graceful shutdown?

### ISSUE THREAD

**Issue by tattsun** [scotty-web/scotty#169]
Hello.
I'm planning to use scotty as a production server, and I have an issue of scotty.

Does scotty support graceful shutdown? or should I use wai middleware such as wai-graceful(https://hackage.haskell.org/package/wai-graceful)?

Thanks.

**Comment by sol** [comment]
If you are hosting at AWS, you can use ELB with connection draining in front of your app to get this for free (same should be true if you have some other means of getting some load balancer in front of you site).

**Comment by tattsun** [comment]
OK, I'll use a load balancer.

Thanks.
