### ISSUE TITLE
Add ability to disable the exception handling framework

### ISSUE THREAD

**Issue by centromere** [scotty-web/scotty#175]
I'm currently fighting with the framework over exception handling. I am using a library which defines and throws its own exceptions within IO, and I'd like to be able to catch and log the exceptions (along with the request that generated it) to a file. Unfortunately, this seems impossible in Scotty due to how liftIO is defined. Currently the exception thrown is converted to a String, thus requiring me to parse the String with `stringError` just to get it back to the original exception that was thrown in the first place.

It would be nice to be able to disable all of this in favor of setOnException/setOnExceptionResponse in Warp.

**Comment by bdesham** [comment]
Would you mind sharing the exception handling you’ve come up with? I think I’m having the same problem—I’m using postgresql-simple and any database errors I run into are being shown to the user!

**Comment by centromere** [comment]
I don't have a solution. If the AMQP connection dies/errors, the result is printed to stdout and there's nothing I can do about it.

**Comment by xich** [comment]
Ugh. Yes, the exception handling needs a complete overhaul. My current plan is something like:

* Remove the special handling in `liftIO` so it acts like one would expect (not catch and convert IO exceptions).
* Add a combinator (`liftIOx`?) to basically do what `liftIO` does now for the simplified Scotty API only (the one with String errors).
* Deprecate `raise`/`rescue` etc for the `ExceptT` equivalents.

If you need to work-around in the meantime, you can change the definition of `liftIO` here:

https://github.com/scotty-web/scotty/blob/master/Web/Scotty/Internal/Types.hs#L153

A simple `liftIO = ActionT . liftIO` should suffice.

**Comment by centromere** [comment]
:+1:

**Comment by centromere** [comment]
Do you think it will be possible to change the `defaultHandler` type to `SomeException -> ActionM ()` instead of `Text -> ActionM ()`?

**Comment by xich** [comment]
The `defaultHandler` exported from `Web.Scotty.Trans` has a more general type... you'll have to make your exception type an instance of `ScottyError`... perhaps that can be done for `SomeException` itself?(I'll explore removing `ScottyError` too. I'm just thinking "in the meantime".)

**Comment by ocramz** [comment]
(8 years later) Hi! The exception system just got a big overhaul : https://github.com/scotty-web/scotty/pull/314
