### ISSUE TITLE
POST requests print to stdout even with verbose turned off

### ISSUE THREAD

**Issue by centromere** [scotty-web/scotty#176]
When a POST request is processed, the string "consuming body" is printed to the screen, even though verbosity is turned off:
https://github.com/scotty-web/scotty/blob/2d3b8d9c32121cfcaa7900981907a3737d7a9dbd/Web/Scotty/Route.hs#L174

**Comment by RyanGlScott** [comment]
Sorry, I've been meaning to look at this. Someone already opened [an issue](https://github.com/scotty-web/scotty/issues/174) about it earlier, so I'll close this one.
