### ISSUE TITLE
Stack: dependencies cannot be resolved

### ISSUE THREAD

**Issue by honza** [scotty-web/scotty#178]
No matter how much stuff you add to `extra_deps`, Scotty won't compile using stack.

**Comment by RyanGlScott** [comment]
I'm not an avid `stack` user, so I need your help to figure out how to reproduce this issue. I might not be doing this right, but after installing `stack`, I tried the following steps, and everything appeared to work:

```bash
stack unpack scotty
cd scotty-0.10.2/
stack init
stack setup
stack build
```

**Comment by honza** [comment]
I created a new project, added scotty 0.10.2 as a dependency and tried to `stack build`. It didn't work at all with the ghc 7.10 resolver. Once I switched to the LTS resolver, I got this:

```
$ stack build
purger-0.1.0.0: build
Preprocessing executable 'purger' for purger-0.1.0.0...
<command line>: cannot satisfy -package-id purger-0.1.0.0-inplace
    (use -v for more information)

--  While building package purger-0.1.0.0 using:
      /Users/honza/.stack/programs/x86_64-osx/ghc-7.10.2/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/honza/.stack/snapshots/x86_64-osx/lts-3.1/7.10.2/pkgdb/ /var/folders/sw/3bt8t1290s1c3tkndq67bfr40000gn/T/stack6246/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build exe:purger --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
```

`purger` is my app that has scotty as a dependency.

**Comment by RyanGlScott** [comment]
Hm, it's hard to say what's going on here. I'm not sure what the GHC 7.10 resolver is, but I did successfully build `scotty` and its test suite with `stack`'s `lts-3.1` setup (although yours clearly failed on `lts-3.1`, as the output demonstrates), in addition to the `lts-3.2` setup that I tried the first time.

I'm tempting to think that there's something going in `purger`'s config that could be causing things to go awry. Would you be able to tell me its dependencies?

**Comment by honza** [comment]
@RyanGlScott Thank you for your patience and willingness to help! I nuked all the stack cache and other misc files, and started over. This time everything worked on the first try. I'm sorry, it was all caused by my environment.
