### ISSUE TITLE
Add a "finish" function

### ISSUE THREAD

**Issue by glasserc** [scotty-web/scotty#186]
When implementing a web service, sometimes you encounter a situation where you detect that some precondition of the service has been violated and you want to terminate the action immediately. A good example is when a resource is missing; you want to produce a 404 response, and skip the rest of the handler.

Doing this with the native ActionT in Scotty isn't really pleasant. Based on https://github.com/scotty-web/scotty/blob/master/examples/exceptions.hs, we've been defining a ScottyError that contains constructors describing the various kinds of HTTP error statuses that our web services might encounter. This is tedious and unnecessary since the space of HTTP statuses is well-known. In fact, you can conceive of the `redirect` function already in Scotty as a built-in example of this that supports only the 302 status.

Therefore, I'd like to propose a "finish" function, inspired by [Snap's finishWith](http://hackage.haskell.org/package/snap-core-0.9.7.0/docs/Snap-Core.html#v:finishWith), which terminates the ActionT immediately. The exact API isn't very important -- it could take a Response, or just use whatever response has been built using the `status`, `setHeader`, and `text` functions, or something else entirely. It could be implemented by adding a `Finished` constructor to the ActionError type. This means using exceptions as flow control, which some people don't like, but we're already doing that using `next` and `redirect`. With such a mechanism in place, it would be possible to add a "batteries included" library that includes a complete collection of HTTP statuses (including classics like `Forbidden`, `Not Authorized`, `Internal Server Error`, etc.).

What do you think? If you're short on time, I'd be happy to try to put together a PR.

**Comment by charles-cooper** [comment]
It's funny, I was about to create an identical issue :).

@glasserc You are right, we already have flow-control verbs in `raise`, `next` and `redirect`. While exceptions as flow control is a style that not everybody likes, short-circuiting implicitly instead of explicitly handling the case is often more convenient. And the API can have both options, just as in monadic code typically you can throw an exception or return a Left and leave the flow control up to the caller.

**Comment by glittershark** [comment]
:+1: this would be really nice to have

**Comment by adamwespiser** [comment]
this would be really good for my project, as well.

**Comment by Dremora** [comment]
Coming from express.js background (which is similar to Sinatra which Scotty is inspired by), the lack of ability to terminate early is the only inconvenience I've struggled with so far. So this one gets my +1 as well.

**Comment by potomak** [comment]
I submitted #188 to include a new `finish` function that should work as described by @glasserc.

Note: also Growler has this feature, see [`abort`](http://hackage.haskell.org/package/growler-0.6.0/docs/Web-Growler.html#v:abort) function.

**Comment by taphu** [comment]
It looks like this issue has been resolved via @potomak 's commit? Maybe it should be closed?

**Comment by seagreen** [comment]
`finish` has definitely [made it onto Hackage](https://hackage.haskell.org/package/scotty-0.11.0/docs/Web-Scotty.html#v:finish), this can be closed.
