### ISSUE TITLE
Routes trying to match too strict?

### ISSUE THREAD

**Issue by SkyWriter** [scotty-web/scotty#189]
Here's an example code:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
import Web.Scotty

import Data.Monoid (mconcat)

main = scotty 3030 $ do
    get "/:word" $ do
        beam <- param "word"
        html $ mconcat ["<h1>Scotty, ", beam, " me up!</h1>"]
```

The following works:

```
$ curl localhost:3030/beam
<h1>Scotty, beam me up!</h1>%
```

But when there's an extra slash, it doesn't:

```
$ curl localhost:3030//beam
<h1>404: File Not Found!</h1>%
```

**Comment by retep007** [comment]
@SkyWriter is this any issue ?  It's like gray side of HTTP RFC 2396 it is just matter of interpretation valid url is "/segment/" which says "//" is valid but not how to deal with it. For me it's fine like it is now.

**Comment by SkyWriter** [comment]
Not much of an issue, really. It's just something that goes against common behavior.

E.g. https://github.com/scotty-web/scotty/ and https://github.com/scotty-web//scotty/ are rendering the same page, and that's pretty much what is happening with most (all?) of other frameworks.

Coming from a Ruby background I could come up with something like:

```
require 'sinatra'

get '/:word' do
  "<h1>Hello, #{params[:word]}!</h1>"
end
```

... And that would yield "Hello, world!" for both `/world` and `//world`. One might argue whether the second one should rather be "Hello, /world!", but getting 404 instead is something surprising. Not shocking since in the end it's a wrong URL, but surprising.

So, the question is: maybe it makes sense to somehow canonize the URL before parsing? Something along the lines of `intercalate "/" . filter (not . null) . splitOn "/"` (which is, like it always does, not covering the necessary corner cases, but delivers the premise).

**Comment by chessai** [comment]
i thought about this and am leaning toward being okay with implementing this or taking a PR, provided tests are written and that it doesn't somehow introduce a vulnerability, which i find extremely unlikely.

**Comment by SkyWriter** [comment]
Submitted a pull request for this. Can you please take a look when you get a minute, @chessai? Thanks!
