### ISSUE TITLE
Add hpc-coveralls as test-suite dependency?

### ISSUE THREAD

**Issue by RyanGlScott** [scotty-web/scotty#191]
As you may have noticed, `scotty` has been experiencing quite a few [Travis CI build errors](https://travis-ci.org/scotty-web/scotty/jobs/103954347), and the culprit is that we have to install both `hpc-coveralls` and `scotty`. Currently, we do this in [separate steps](https://github.com/scotty-web/scotty/blob/eee556aeab557083e39226e154bfece67a69d945/.travis.yml#L28) in `.travis.yml`, so if `hpc-coveralls`'s dependencies have a more lenient build plan than that of `scotty`'s dependencies (as is currently the case, since various dependencies have different upper bounds on `transformers-compat`), than we get an error by the time we try to install `scotty`.

There is a way to fix this: we would have to install `hpc-coveralls` _and_ `scotty` in one go. Unfortunately, I don't think it's possible to do something like this:

```haskell
cabal install 'scotty --enable-tests' hpc-coverals
```

That is, where you only enable tests on one particular target of `cabal install`. As a workaround, what about this idea? We change `scotty`'s test suite in `scotty.cabal` to add the following lines:

```
flag hpc-coveralls
  default: False
  description: Install hpc-coveralls as a part of the test suite.
  manual: True

if flag(hpc-coveralls)
  build-depends: hpc-coveralls
```

This way, we won't impose an `hpc-coveralls` dependency on most users, but for the particular case of testing `scotty` on Travis CI, all we'd have to do is `cabal install --enable-tests -fhpc-coveralls`. This would also have the fortunate side-effect of allowing us to cache _all_ of `scotty`'s dependencies on Travis for future builds (using the new `multi-ghc-travis` setup).

**Comment by xich** [comment]
Why add a flag? Why don't we just add `hpc-coveralls` to the `build-depends` of the `test-suite` target? Regular users won't be affected because `--enable-tests` is not on by default, right?

**Comment by RyanGlScott** [comment]
> Why add a flag?

It makes it much quicker to validate the test suite locally, since you don't have to install all of `hpc-coveralls`. But I don't have a particularly strong opinion on the matter, so I'd be happy either way.

**Comment by xich** [comment]
Ah true.

I'm just mostly worried that having a flag would cause travis to build with a different dependency solution than the local tests would... but maybe that would only catch strictly more failures and be a better thing anyway.

I just added it as a dependency for now, since we only pay the price of installing it once. If it becomes problematic build-time-wise we can reconsider.
