### ISSUE TITLE
Sending an email

### ISSUE THREAD

**Issue by Miguelme** [scotty-web/scotty#195]
Is it possible to send an email using scotty ? How is the proper way to achieve sending an email ?

**Comment by edofic** [comment]
I think email is out of scope for a mini web framework like scotty. You should probably use an email library - [smtp-mail](https://hackage.haskell.org/package/smtp-mail) for example.

**Comment by chrissound** [comment]
Shall we close this issue?

**Comment by chessai** [comment]
Closing. Out of scope.
