### ISSUE TITLE
`matchAny` does not match any HTTP method.

### ISSUE THREAD

**Issue by taphu** [scotty-web/scotty#196]
The documentation for `matchAny` claims:

> Add a route that matches regardless of the HTTP verb.

but this isn't true. The implementation only matches standard verbs, defined in `Network.HTTP.Types.Method.StdMethod`.

see: https://github.com/scotty-web/scotty/blob/cd713b14b560bf0168bd5dd8955d0e35fb84f329/Web/Scotty/Route.hs#L60

The `[minBound..maxBound]` on that line is a list of `StdMethod`s, which of course is not all possible HTTP verbs.

**Comment by taphu** [comment]
I didn't get a chance to finish it tonight, but I have a PR coming, FYI.

**Comment by taphu** [comment]
Added a PR: https://github.com/scotty-web/scotty/pull/197 which is minimally invasive and makes no changes to the interface.

**Comment by taphu** [comment]
I wonder if anyone else has an opinion on this. :-)

**Comment by xich** [comment]
Thanks for the patch and the test! (and the ping ;-))
