### ISSUE TITLE
Need documentation like Playframework docs (https://www.playframework.com/documentation/2.5.x/Home)

### ISSUE THREAD

**Issue by pamu** [scotty-web/scotty#201]
My Startup want to use Haskell instead of Scala. We use playframework a lot and We are trying to give Haskell Web programming a Shot. If we are happy with it. We would like to migrate all of our codebase to Haskell from Scala. We use micro service architecture, So, we are thinking of using Scotty. But there is no proper documentation on the internet. It is so frustrating coming from Playframework ecosystem. Play has beautiful documentation (https://www.playframework.com/documentation/2.5.x/Home).

All I see is old documentation which is not complete and absolutely not useful. I don't think any framework will be useful without proper documentation or tutorials. I strongly recommend good, complete and latest documentation. All my enthusiasm for Haskell got killed after seeing the how bad the documentation is for web frameworks in Haskell. This way Haskell will always be the language few people use and will not grow.

**Comment by xich** [comment]
I'm happy to accept patches for any updates to the documentation you wish to make.

Given Scotty is barely 1000 lines, half of which is already documentation, I doubt it'd be good material for an O'Reilly book.
