### ISSUE TITLE
"Setting phasers to stun..." Alternative

### ISSUE THREAD

**Issue by I3ck** [scotty-web/scotty#202]
I'd like to disable the "Setting phasers to stun" output or use my own.  
Can't find a way to currently do that

**Comment by RyanGlScott** [comment]
You can do this with [`scottyOpts`](http://hackage.haskell.org/package/scotty-0.11.0/docs/Web-Scotty.html#v:scottyOpts) by setting the verbosity to 0:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Web.Scotty

import Data.Default.Class (def)
import Data.Monoid (mconcat)

main = scottyOpts def{verbose=0} $ do
  get "/:word" $ do
    beam <- param "word"
    html $ mconcat ["<h1>Scotty, ", beam, " me up!</h1>"]
```

**Comment by I3ck** [comment]
Nice, thanks.
Is there a way to also set the port without having to include / directly define https://hackage.haskell.org/package/warp-3.2.9/docs/Network-Wai-Handler-Warp-Internal.html#t:Settings ?

**Comment by RyanGlScott** [comment]
`scotty` usually just uses the `defaultSettings` for `warp`, so you can configure its port like so:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import Web.Scotty

import Data.Default.Class (def)
import Data.Monoid (mconcat)
import Network.Wai.Handler.Warp (Settings, defaultSettings, setPort)

main = scottyOpts def{ verbose=0, settings=setPort 3000 defaultSettings } $ do
  get "/:word" $ do
    beam <- param "word"
    html $ mconcat ["<h1>Scotty, ", beam, " me up!</h1>"]
```

**Comment by I3ck** [comment]
Works perfectly. Thanks for the help
