### ISSUE TITLE
Request for code snippet - Recommended way to host application and enable websockets

### ISSUE THREAD

**Issue by ThomasLocke** [scotty-web/scotty#207]
Something akin to this https://www.paramander.com/blog/playing-with-websockets-in-haskell-and-elm but  with scotty doing the html/js hosting.

**Comment by tungd** [comment]
You can use `scottyApp` to turn you Scotty application into WAI one, from this point it is exactly the same as the code you linked. For example:

```haskell
main :: IO ()
main = do
  state <- Concurrent.newMVar []
  Warp.run 3000 $ WS.websocketsOr
    WS.defaultConnectionOptions
    (wsApp state)
    httpApp

httpApp = scottyApp $ do
  get "/" $ do
    text "Hello, World"
```

**Comment by ThomasLocke** [comment]
Well, that was amazingly simple! Thanks.  :)
