### ISSUE TITLE
Question: What does "Scotty is set up by default for development mode" mean?

### ISSUE THREAD

**Issue by ThomasLocke** [scotty-web/scotty#213]
While working on my first Scotty project, I noticed the above sentence early in the stackage.org docs:

https://www.stackage.org/haddock/lts-10.5/scotty-0.11.0/Web-Scotty.html

> Scotty is set up by default for development mode. For production servers, you will likely want to modify settings and the defaultHandler. See the comments on each of these functions for more information.

I get the need to set the `defaultHandler` but I can't quite figure out what needs to be changed in `settings` in order to go from "development" to "production".

To my untrained eye, the default settings seems quite sane and fine for a production server.

Or am I missing something?

**Comment by mordae** [comment]
Citing [the docs](http://hackage.haskell.org/package/scotty-0.11.3/docs/Web-Scotty.html#t:Options):
> Note: to work around an issue in warp, the default FD cache duration is set to 0 so changes to static files are always picked up. This likely has performance implications, so you may want to modify this for production servers using [setFdCacheDuration](http://hackage.haskell.org/package/warp-3.2.26/docs/Network-Wai-Handler-Warp.html#v:setFdCacheDuration).

**Comment by ThomasLocke** [comment]
And with that out of the way, I think we can safely close this "issue".  :)
