### ISSUE TITLE
Is it possible to read the response header within a route or the error handler?

### ISSUE THREAD

**Issue by zhangchiqing** [scotty-web/scotty#214]
[The current API] allows me to read request header to set response header, but is it possible to read **response header** which I set earlier in a middleware?

My use case is that: I'd like to have a middleware that generates a uuid as request id, and add it to the response header. If I can read the response header in the error handler, then I can print the error along with the request id. Does it make sense?

**Comment by ocramz** [comment]
Since scotty-0.20 the Response is part of ActionEnv record so implementing this would be very simple.
