### ISSUE TITLE
Middleware, actions and Vault

### ISSUE THREAD

**Issue by dpwiz** [scotty-web/scotty#22]
I've tried to extract my code and put it into middleware, but can't quite wrap my head around Vault thing. It is quite cryptic by itself with that `Key a` and having to fetch a request, then extract vault record to do a thing not adding to simplicity at all. I think we can do better than that. (:

I propose adding some helpers like `getVault`/`putVault` to work in a middleware context and `lookVault` for actions to operate on middleware-provided values.

I will try to make a patch if i will suceed in my authMiddleware musings...

**Comment by chessai** [comment]
Closing dormant/seemingly resolved issue
