### ISSUE TITLE
Cabal metadata revision without hpc-coveralls

### ISSUE THREAD

**Issue by endgame** [scotty-web/scotty#224]
If there are no releases imminent, it would be handy to have a metadata revision without hpc-coveralls pushed to hackage.

Reason: it makes things a bit awkward in nixpkgs. cabal2nix doesn't understand optional dependencies very well, and generates a derivation that wants hpc-coveralls. https://github.com/NixOS/nixpkgs/pull/53627 makes hpc-coveralls build, but it would be nicer if we didn't build it at all.

**Comment by RyanGlScott** [comment]
I've uploaded [`scotty-0.11.3`](http://hackage.haskell.org/package/scotty-0.11.3) to Hackage, which does not depend on `hpc-coveralls` at all.

**Comment by endgame** [comment]
Thanks mate.
