### ISSUE TITLE
Better error message when no data is provided to jsonData

### ISSUE THREAD

**Issue by ad-si** [scotty-web/scotty#226]
e.g. `http post :3000/item` without providing any data will show following error:
```
<h1>500 Internal Server Error</h1>
jsonData - no parse: Error in $: not enough input. Data was:
```
Which isn't really helpful. It should say something like `No data was provided`

**Comment by chessai** [comment]
The problem with this is that the error message you're seeing is from aeson, and returned to us as a string. I'm loathe to parse that string and return an error like this.

**Comment by chessai** [comment]
Oh, wait, sorry. You're talking about the bit at the end. Yeah, this is totally doable.
