### ISSUE TITLE
Adding a contributing page?

### ISSUE THREAD

**Issue by devjames25** [scotty-web/scotty#230]
I noticed that this project lacks a contributing page. This can be confusing for a first time user who wants to contribute if they have interest in the project. I suggest that a short summary on the README would give users a general idea on how to step in and contribute right away.

**Comment by fumieval** [comment]
There's a section in the README, but it's a bit too terse. Adding the list of contributors might help.

``
Development & Support

Open an issue on GitHub.
```

**Comment by ocramz** [comment]
Now we have labeled issues and a Contributing section in the Readme!
