### ISSUE TITLE
Web server reload on file change

### ISSUE THREAD

**Issue by alexander-myltsev** [scotty-web/scotty#231]
Hi,

Why Scotty doesn't have the means to reload the binary on file changes?

Do you use something else to watch file changes?

**Comment by cfraz89** [comment]
Try http://eradman.com/entrproject/

**Comment by chessai** [comment]
I believe this isn't a deficiency of scotty. Like @cfraz89 mentioned, `entr` is a viable option. using plain `ghcid` is also a good option. Here are examples, assuming a cabal project (i don't use stack but i'm sure some stack user could provide a solution)

entr:
```bash
ag -l | entr -s 'runghc Setup.hs configure --disable-optimization && runghc Setup.hs build <exe_name> && dist/build/<exe_name>/<exe_name>
``

ghcid:

```bash
runhaskell Setup.hs configure && \
  ghcid \
    -c "runhaskell Setup.hs repl" \
    --reload="static/" \ # reload static assets in static/ dir
    --run="Main.main"
```

I prefer ghcid since it doesn't have to configure and build on each save, it just runs bytecode. This is faster even if you disable optimisations. The drawback is that it won't reload on changes to your cabal file, and it's harder to specify a precise set of files on which you want to reload. The ag+entr version provides this.

**Comment by soywod** [comment]
I use scotty on stack, and it works like a charm with `entr` (thanks @cfraz89). Here my script (I don't think I have the best approach, but for now it fits my needs):

```bash
# server is the name of my executable
ls src/**/*.hs | entr -s "pkill server; stack run &"
```
