### ISSUE TITLE
Seeking Maintainers

### ISSUE THREAD

**Issue by xich** [scotty-web/scotty#234]
At this point, I haven't used Scotty for years. Other than @RyanGlScott's heroic efforts (thanks!) to keep it compiling, it's basically been abandonware since ~2014. That's not great.

I'm happy to add maintainers to the github project if someone would like to step up to take things over. Ideally, if you volunteer you'll respond to PRs faster than I have :-), and otherwise commit to owning its future.

Comment below if you are interested.

**Comment by chessai** [comment]
I use scotty, and I regulary introduce people (mostly interns) to Haskell web programming with it. I am definitely interested in aiding in its maintenance.

**Comment by xich** [comment]
@chessai Thanks! Added you as a maintainer to the github org. Let me know if that doesn't cover something.
