### ISSUE TITLE
Example of how to test app with state

### ISSUE THREAD

**Issue by tomasaschan** [scotty-web/scotty#240]
The example in [globalstate.hs](https://github.com/scotty-web/scotty/blob/master/examples/globalstate.hs) is very instructive, but I'm really struggling with how to write tests for an application built like that.

Testing app responses is not so difficult, using [hspec-wai](https://hackage.haskell.org/package/hspec-wai-0.10.1/docs/Test-Hspec-Wai.html#v:with), but I can't figure out how to write the tests to enable me to verify state updates as well. Would it be possible to add an example that tests the sample app from `globalstate.hs`, that shows how to test both request/response interactions as well as setting upp a state, making a request and verify that the new state is the expected one?

Thanks a lot!

**Comment by ocramz** [comment]
@tomasaschan this one is tricky because StateT in the presence of async exceptions does not behave well.

The "ReaderT pattern" with a thread-safe TVar holding state as shown in globalstate.hs is actually best practice for this case.

**Comment by tomasaschan** [comment]
Thanks!

This issue is four years old, and I have no idea any longer in what context I was asking the question, whether I figured this out out on my own or moved on to use something different. Thus, I also have no way of knowing whether your answer is useful to anyone else having similar questions.

So I'll close this issue for housekeeping.

Thanks for taking the time to answer anyway!
