### ISSUE TITLE
reduce cpp

### ISSUE THREAD

**Issue by chessai** [scotty-web/scotty#252]
plan: move to http-types >= 0.11, wai to >= 3.2.2

@RyanGlScott what's your opinion on dropping GHC 7.6.3 and 7.8? because of prelude-compat it's not hard to support those. really the only annoyance is when i screw up and CI fails.

**Comment by RyanGlScott** [comment]
Dropping support for 7.6 and 7.8 sounds fine to me.

**Comment by chessai** [comment]
that's my preference too.

i'm working up toward one big majour release with a lot of improvements, so breaking changes make sense to do now.

**Comment by ocramz** [comment]
@chessai we've now restricted CI to GHC >= 8.10 , what should we do with this ticket?

**Comment by ocramz** [comment]
Big step forward in #333 . Closing this!
