### ISSUE TITLE
add cookie support

### ISSUE THREAD

**Issue by chessai** [scotty-web/scotty#253]
see #47 and #69 (nice)

**Comment by ocramz** [comment]
@chessai there's a single-module `scotty-cookie` package which leverages `cookie` :

https://hackage.haskell.org/package/scotty-cookie-0.1.0.3/docs/Web-Scotty-Cookie.html

`scotty-cookie` hasn't been updated since 2015 ; I wonder if we could take inspiration from that?

**Comment by chessai** [comment]
@ocramz sounds like a pretty good idea. Interested in a PR?

**Comment by ocramz** [comment]
@chessai this is fixed now! 👍
