### ISSUE TITLE
old massive PRs

### ISSUE THREAD

**Issue by chessai** [scotty-web/scotty#256]
@RyanGlScott there are a lot of very old, open, massive PRs. My strategy thus far has just been to close them and open an issue. It's not clear to me that any of them are actually useful as of now, since most of the work was done for some very old version of scotty. Perhaps you have some more insight on this

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. With a project as old as `scotty`, sometimes it's therapeutic just to close a bunch of old issues in order to clean up the cobwebs. If the reporter really cares about their closed PR, I'm sure they'll chime in at some point :)

**Comment by chessai** [comment]
Okay, since we're in agreement i will close this then.
