### ISSUE TITLE
Scotty vs. WAI 3.0 continuation-passing style

### ISSUE THREAD

**Issue by florpe** [scotty-web/scotty#260]
I've been trying unsuccessfully to write a function ScottyM () -> ActionM () (or WAI.Application -> ActionM (), really) in order to use Scotty applications as plugins. As far as I can tell the main difficulty with this is that Scotty still uses the pre-WAI 3.0 style of application internally. Is there a technical reason for this, or would it be worthwhile to try and migrate Scotty to CPS?

**Comment by chessai** [comment]
Investigating this might be worthwhile. The design of scotty is pretty old, and I have gripes with a lot of it.

**Comment by jfraudeau** [comment]
Not sure how it relates to WAI 3.0 but it looks like the use case was implemented in https://github.com/scotty-web/scotty/pull/233

@florpe If it is still relevant to you can you confirm ?

**Comment by ocramz** [comment]
Yep, now we have `nested` as @jfraudeau pointed out. Thanks!
