### ISSUE TITLE
Make a new Hackage release

### ISSUE THREAD

**Issue by maksbotan** [scotty-web/scotty#263]
Hi @RyanGlScott @chessai,

Can you please make a new Hackage release? In #232 in December you mentioned that you plan a new version "soon", but this does not seem to have happened yet.

If there are any major blockers, maybe you can use some help in solving them?

**Comment by chessai** [comment]
@maksbotan thanks for raising this issue. Indeed the ball was dropped and I waited too long. There was a lot more work I wanted to do for the 0.12 release, but I think that work will come a bit slower than expected. I just tried to upload scotty to hackage, but it seems i don't yet have upload permissions. Once #264 is resolved i will upload it. Thanks!

**Comment by chessai** [comment]
Uploaded!

**Comment by maksbotan** [comment]
Thanks! Much appreciated.
