### ISSUE TITLE
error downloading scotty with stack build

### ISSUE THREAD

**Issue by TehJunn** [scotty-web/scotty#271]
![image](https://user-images.githubusercontent.com/73212221/103270614-5b3b7280-4986-11eb-86c0-5ca60d80a451.png)

regex-posix > C:\Users\Jordan\AppData\Local\Temp\stack-bb048b3d2173b0fb\regex-posix-0.96.0.0\Wrap.hsc:96:10: fatal error: regex.h: No such file or directory

this seems to be the part that is failing i checked and like it said there is no such file directory i tried just trying to make one but that didnt work because one of the folder names in this case "stack-bb048b3d2173b0fb" seems to be randomly generated because every time i try to run *stack build scotty* in stack ghci that file name changes (probably so idiots like me dont do this)

**Comment by fumieval** [comment]
Please see https://github.com/haskell-hvr/regex-posix/issues/4; it's not a problem in this package itself
