### ISSUE TITLE
Does Scotty still have hopes of being maintained or is it officially abandoned?

### ISSUE THREAD

**Issue by JivanRoquet** [scotty-web/scotty#274]
Last commit Sep 2020.
Last closed issue Aug 2020.
Last reply on an open issue May 2020.

Any plans to rise this excellent micro-framework back from its grave? Or is it officially over?

**Comment by RyanGlScott** [comment]
I'm not really a maintainer—I bequeathed that title to @chessai—but I wouldn't call `scotty` abandoned. Life gets busy sometimes, and it's possible that maintenance of `scotty` had to take a backseat. I'll give @chessai an opportunity to chime in, but if there isn't enough time to devote to maintenance (which I could understand), I'd be willing to help find additional maintainers.

**Comment by JivanRoquet** [comment]
Well I could help on some stuff if I get a good enough indication that a PR would be reviewed.

In this particular case I was wondering if there's any way to avoid sending error messages in HTML (e.g. errors generated by Aeson failing to parse `jsonData`, resulting in a 422 Unprocessable Entity), but have them returned as JSON instead. Maybe such capability already exists, but I couldn't find it anywhere in the docs. If you can point me to how to do this, I could then add it to the examples. If it doesn't exist I'd be glad to make a PR in this direction.

**Comment by chessai** [comment]
Scotty has indeed taken a backseat for me. I think we should find more maintainers. I can help review PRs and issues still, but the time investment for me that makes sense has decreased significantly.

**Comment by RyanGlScott** [comment]
Sorry for the delay on this. I've sent a [post to the haskell-cafe mailing list](https://mail.haskell.org/pipermail/haskell-cafe/2021-May/133969.html) to try and find additional maintainers.

**Comment by RyanGlScott** [comment]
Welcome @friedbrice and @fumieval as new maintainers! I think we're at a healthy number of maintainers now, so I'm going to close this issue.

**Comment by 2mol** [comment]
Thanks and big respect to the new maintainers for stepping up! May I suggest that you bring scotty as a project to the ZuriHac hackathon (https://zurihac.com) in a month? I'm sure you would find a couple of willing contributors. It could be fun to do a concerted push over that weekend, like triaging/closing issues, improving docs, and so on.

**Comment by friedbrice** [comment]
Hi @2mol, thanks for the great idea! At this point, I don't think we can commit to ZuriHac, until at least I get a bit more familiar with the codebase and do a bit of research into what's involved. But it's a great idea, and I will be looking into it to see if we can make it happen!

**Comment by shiraeeshi** [comment]
@friedbrice, can you also make notes while you're getting familiar with the codebase and share them later?
There is an article called "Read you a Scotty" (https://devanla.com/pages/lys.html), I haven't read it, so I don't know if it's good or not, I found it after I saw the post about call for maintainers. Perhaps it will be helpful.
@RyanGlScott, is there a point in commit history where the project is the most simple and easy to understand? Maybe one of the first commits?

**Comment by 2mol** [comment]
@friedbrice yeah, no commitment necessary :)

I think you could even just come and learn in public. There might also be people to learn from, but either way, no pressure and no expectations! Happy hacking!
