### ISSUE TITLE
Is there any documentation on how to test Scotty endpoints?

### ISSUE THREAD

**Issue by JivanRoquet** [scotty-web/scotty#275]
With the following endpoint:

```haskell
myendpoint :: Text -> ScottyM ()
myendpoint info =
    post "/foo/bar/:var" $ do
        var :: Text <- param "var"
        query :: Query <- jsonData
        result <- liftIO $ retrieveResult info var query
        json $ result

runApi :: IO ()
runApi = scotty 4602 $ do
    myendpoint
```

How to test `myendpoint` with different possible inputs, for instance:

```haskell
info1 = "foo"
query1 = Query { qParam1 = "foo", qParam2 = "bar" }
var1 = "bar"
expect1 = Result { foo = "foo", bar = "bar" }

res1 = decode $ test_myendpoint info1 query1 var1
res1 `shouldBe` expect1

info2 = "baz"
query2 = Query { qParam1 = "hello", qParam2 = "there" }
var2 = "boo"
expect2 = Result { foo = "biz", bar = "dev" }

res2 = decode $ test_myendpoint info2 query2 var2
res2 `shouldBe` expect2
```

  [1]: https://hackage.haskell.org/package/scotty

**Comment by RyanGlScott** [comment]
I think you may be looking for the functionality provided by the [`hspec-wai`](https://hackage.haskell.org/package/hspec-wai-0.11.1/docs/Test-Hspec-Wai.html#v:shouldRespondWith) library. In particular, the [`shouldRespondWith` function](https://hackage.haskell.org/package/hspec-wai-0.11.1/docs/Test-Hspec-Wai.html#v:shouldRespondWith) may be what you are looking for. There are examples of `shouldRespondWith` being used in [`scotty`'s test suite](https://github.com/scotty-web/scotty/blob/3aac9ccaa0cc7b4dbd5736f04528ca6b80bb992a/test/Web/ScottySpec.hs#L100-L109).

**Comment by JivanRoquet** [comment]
Well, thanks for the answer obviously. However this lib doesn't seem to allow inspecting the response provided by the endpoint, instead just checking that it's equal to some value. E.g. you can't do "assert that this JSON list has 5 elements in it and they're all Int's".

In the end I simply chose to run the API for real and query it with a regular http client.

**Comment by ocramz** [comment]
@JivanRoquet I suppose it's ultimately a matter of taste here (in addition to engineering elbow grease and OSS maintainership work), but `aeson`'s responsibility ends at "this response can be parsed as JSON and if not, here's an error". Any validation is up to the user.

You might want to add something like https://hackage.haskell.org/package/hspec-golden-aeson to your project for that.

**Comment by ocramz** [comment]
At present, the best documentation is our [test suite](./test/Web/ScottySpec.hs) and our [examples](.examples/).
