### ISSUE TITLE
Additional maintainer needed?

### ISSUE THREAD

**Issue by ocramz** [scotty-web/scotty#298]
Hi @xich @fumieval @RyanGlScott @chessai I would like to offer myself as maintainer and help see through PRs and releases.
I use scotty in all my projects that have a web component and would hate to see it bitrot.

My username on Hackage is https://hackage.haskell.org/user/ocramz .

Thanks!

**Comment by chessai** [comment]
> Hi @xich @fumieval @RyanGlScott @chessai I would like to offer myself as maintainer and help see through PRs and releases.
> I use scotty in all my projects that have a web component and would hate to see it bitrot.
> 
> My username on Hackage is https://hackage.haskell.org/user/ocramz .
> 
> Thanks!

I've added you on hackage.

**Comment by RyanGlScott** [comment]
Thanks for offering to be a maintainer, @ocramz! I've granted you the appropriate GitHub permissions as well.

**Comment by chessai** [comment]
> Thanks for offering to be a maintainer, @ocramz! I've granted you the appropriate GitHub permissions as well.

Oops, thought you already had those. Thanks @RyanGlScott !

**Comment by ocramz** [comment]
Thank you both! 🚀
