### ISSUE TITLE
`ActionT`'s `MonadFail` instance removed in `scotty-0.20`

### ISSUE THREAD

**Issue by RyanGlScott** [scotty-web/scotty#323]
PR #314 removed the `MonadFail` instance for `ActionT`, which I noticed when trying to upgrade one of my projects:

```
[2 of 2] Compiling Web.Scotty.Comet ( Web/Scotty/Comet.hs, interpreted )

Web/Scotty/Comet.hs:157:28: error:
    • No instance for (MonadFail
                         (Web.Scotty.Internal.Types.ActionT IO))
        arising from a use of ‘fail’
    • In the first argument of ‘($)’, namely ‘fail’
      In the expression:
        fail $ "Expected Object, received: " ++ show wrappedVal
      In a case alternative:
          _ -> fail $ "Expected Object, received: " ++ show wrappedVal
    |
157 |                       _ -> fail $ "Expected Object, received: " ++ show wrappedVal
    |                            ^^^^
```

This isn't documented in the `CHANGELOG` as a breaking change, so I'm unclear if this was intentional or not. If it was intentional, could you document in this in the `CHANGELOG` and suggest a recommended alternative?

**Comment by ocramz** [comment]
Fixed this in #326

**Comment by ocramz** [comment]
@RyanGlScott does 0.20.1 work fine for you now?

**Comment by RyanGlScott** [comment]
I did some preliminary testing, and my projects all build without issue using `scotty-0.20.1`. Thanks!
