### ISSUE TITLE
Raise `scotty-0.20`'s lower version bounds on `base`

### ISSUE THREAD

**Issue by RyanGlScott** [scotty-web/scotty#324]
As discovered in [this CI job](https://github.com/ku-fpg/javascript-bridge/actions/runs/6392296382/job/17349269222#step:17:38), `cabal` can pick a build plan with `scotty-0.20` and GHC 8.4, even though 8.4 doesn't support building `scotty-0.20`:

```
Failed to build scotty-0.20.
Build log ( /github/home/.cabal/logs/ghc-8.4.4/scotty-0.20-6d4ed606ddf8cc6e1fb58b8a4a4553c26e357584de0804cc06b6bd01dcc3e932.log ):
Configuring library for scotty-0.20..
Preprocessing library for scotty-0.20..
Building library for scotty-0.20..

Web/Scotty/Internal/Types.hs:5:14: error:
    Unsupported extension: DerivingVia
  |
5 | {-# language DerivingVia #-}
  |              ^^^^^^^^^^^
```

Can you raise `scotty-0.20`'s lower version bounds on `base` to `>=4.12` to reflect this? Actually, it might even be worth raising it to `>=4.14`, since [this PR](https://github.com/scotty-web/scotty/pull/300) indicates that only GHC 8.10 and later are officially supported.

**Comment by ocramz** [comment]
Ah yes, I added DerivingVia because I wanted to autoderive the Alternative instance of ActionT via Ap but I ended up writing the instance by hand. Sorry!

**Comment by ocramz** [comment]
I've made a revision to scotty-0.20, now base >= 4.14 .
