### ISSUE TITLE
Document exception handling logic

### ISSUE THREAD

**Issue by ocramz** [scotty-web/scotty#335]
I think we should have a couple examples at the top of the Haddocks, or doctests even better, that show what to expect from the new exception handling logic. 

closes #237

**Comment by zachary822** [comment]
I was about to ask this and then I found this issue. Can you give a small example of catching all errors indiscriminately?

**Comment by ocramz** [comment]
#237 should be implemented as an additional case in the `exceptions` example binary

**Comment by ocramz** [comment]
@zachary822 the example binaries are all up to date with the library, could you share what questions/doubts you have about exception handling?

**Comment by zachary822** [comment]
I have managed to figure it out. Thank you!
