### ISSUE TITLE
Reimplement `ScottyT` in terms of ReaderT

### ISSUE THREAD

**Issue by ocramz** [scotty-web/scotty#340]
This would give us `local`, allowing to apply specific middlewares (e.g. authentication) only on given sets of routes (See #187 ).

Also it would let us unify the exception handling mechanism.

It's only a breaking change if we put the reader variable inside a TVar and some modifying functions gain a MonadIO constraint.

We can use the predicates defined here to inspect HTTP status codes and act accordingly (i.e. throw an exception or not): https://hackage.haskell.org/package/http-types-0.12.3/docs/Network-HTTP-Types-Status.html#v:statusIsInformational 

---

<img width="504" alt="Screenshot 2023-10-15 at 13 39 35" src="https://github.com/scotty-web/scotty/assets/5902760/1a6180f4-60ec-4a6e-a4f3-cb9cd6249ffe">

```
It was ReaderT all along?
```
```
Always has been.
```

**Comment by ocramz** [comment]
@fumieval  what do you think?

**Comment by fumieval** [comment]
ScottyT has nothing to with exceptions because it should never fail, as its sole purpose is to build a WAI application. For this purpose I think State-like monad is a better fit

**Comment by ocramz** [comment]
good points! While I'm a bit concerned by that "should never fail", I don't
have a counterexample currently, so I'll close this.

**Comment by fumieval** [comment]
If the route definition contains a mistake (e.g. `get "/foo"` defined twice), perhaps it should throw an error. It should not be caught anyway

**Comment by ocramz** [comment]
ok, closing this !
