### ISSUE TITLE
Is MonadReader ActionEnv (ActionT m) a good idea?

### ISSUE THREAD

**Issue by fumieval** [scotty-web/scotty#342]
I noticed that I have to `lift` all `ask`s in my code because I'm using `RIO` as a base monad of `ActionT`. Given that `ActionEnv` is an internal structure, inheriting the `MonadReader` instance of the base monad seems more convenient (also brings back the pre-0.20 behaviour).

**Comment by ocramz** [comment]
makes a lot of sense.
