### ISSUE TITLE
Not able to rewrite the query string using Network.Wai.Middleware.Rewrite

### ISSUE THREAD

**Issue by zachary822** [scotty-web/scotty#348]
https://hackage.haskell.org/package/wai-extra-3.1.13.0/docs/Network-Wai-Middleware-Rewrite.html

This only updates the `Request.queryString` and doesn't update `Request.rawQueryString`, therefore scotty routes don't pickup on the rewritten `queryString` and continues to read from the old `rawQueryString`.

According to https://hackage.haskell.org/package/wai-3.2.3/docs/Network-Wai.html#v:rawQueryString `rawQueryString` should not be modified.

I'm thinking we should read from queryString instead, to allow for people that need to modify the queryString while keeping rawQueryString read-only.

**Comment by ocramz** [comment]
Thank you for filing this!

**Comment by ocramz** [comment]
@zachary822 would you be able to provide a minimal repro for this? Thanks!

**Comment by ocramz** [comment]
The solution seems to be fixing this line only: https://github.com/scotty-web/scotty/blob/e6a97352229d9e1811193ff93d2eccf7e1ab9526/Web/Scotty/Route.hs#L163C22-L163C22

**Comment by zachary822** [comment]
I made a simple fix.
