### ISSUE TITLE
Exception information is lost

### ISSUE THREAD

**Issue by cblp** [scotty-web/scotty#372]
When any unknown exception happens, [someExceptionHandler](https://github.com/scotty-web/scotty/blob/66d60f7a6828c7e9f8c7d2dc49e9597e7278b982/Web/Scotty/Action.hs#L116) catches it and drops all information.

So I don't know how to put it in log to investigate. If it's possible please tell how.

Also, [unhandledExceptionHandler](https://github.com/scotty-web/scotty/blob/66d60f7a6828c7e9f8c7d2dc49e9597e7278b982/Web/Scotty/Trans.hs#L133) has no sense because `scottyExceptionHandler` already caught all `ScottyException`s.

**Comment by cblp** [comment]
At least, print SomeException to stdout when `verbose` is on.

**Comment by ocramz** [comment]
Could you share a minimal repro (or even better, a PR with a test case)?

**Comment by ocramz** [comment]
@cblp I agree we could be logging and not dropping information in handlers (PRs welcome!)

I don't agree with the assessment re. unhandledExceptionHandler because there are effects outside ActionT as well.

**Comment by cblp** [comment]
@ocramz see #373. It's not exactly what I mean, but related. I don't know how to test existence/absence of `putStr`.

**Comment by ocramz** [comment]
@cblp good point about `verbose` too. Currently, `verbose` does nothing useful apart from toggling the initial banner and should definitely be improved.

**Comment by cblp** [comment]
> @cblp good point about `verbose` too. Currently, `verbose` does nothing useful apart from toggling the initial banner and should definitely be improved.

See #374

**Comment by ocramz** [comment]
closed by #374
