### ISSUE TITLE
warp-3.4 not accepted

### ISSUE THREAD

**Issue by ysangkok** [scotty-web/scotty#383]
It would be nice to accept the new warp release:

```
% cabal get scotty
Downloading  scotty-0.22
Downloaded   scotty-0.22
Unpacking to scotty-0.22/
% cd scotty-0.22 
% cabal outdated
Outdated dependencies:
warp >=3.0.13 && <3.4 (latest: 3.4.0)
```

stackage issue:

* https://github.com/commercialhaskell/stackage/issues/7287

**Comment by ocramz** [comment]
"outdated" in what sense? CI tests against GHC up to 9.8.2

**Comment by ocramz** [comment]
@ysangkok  I've removed UBs on warp for scotty-0.21 and 0.22 as a Hackage metadata revision. BTW I'm also [not a fan of dependency UBs](#371 )

**Comment by ysangkok** [comment]
Thank you!
