### ISSUE TITLE
Should a scotty github group be made?

### ISSUE THREAD

**Issue by dmjio** [scotty-web/scotty#56]

**Comment by chessai** [comment]
This has already been done

**Comment by dmjio** [comment]
@chessai (cc @xich) everybody was kicked out of the group though.

![image](https://user-images.githubusercontent.com/875324/68777966-7ae7ce00-0600-11ea-86d2-2b053a4d033c.png)

**Comment by chessai** [comment]
@dmjio i'm not sure what happened there. i tried to add you back but i can't. perhaps @xich knows what's up.

**Comment by xich** [comment]
@dmjio I cleaned house, because almost everyone was inactive for years. I reinstated you.

I'd also like to clean up the various repos that have been dormant. I think anything with no commits in last three years can probably go. Objections?

**Comment by dmjio** [comment]
@xich you're the best, thanks! :) I'm fine with the house getting cleaned. It seems people still download the scotty-starter project. I could upgrade things to the latest to make it easier for newcomers. 
![image](https://user-images.githubusercontent.com/875324/68789151-e175e780-0612-11ea-85e0-06b979f2616d.png)
Otherwise, I have no objections whatsoever to anything. Cheers !
