### ISSUE TITLE
Better Type-Safety when routing.

### ISSUE THREAD

**Issue by AndrewRademacher** [scotty-web/scotty#60]
I've set up a project with samples of how routing is accomplished in the major players (Happstack, Snap and Yesod).  The programs should produce more-or-less identical results.  My aim is to get your feed back on how routing in Scotty should look as to be as concise and type-safe as possible.

[routing-comparison](https://github.com/AndrewRademacher/routing-comparison)

Line Up:
- [Happstack](https://github.com/AndrewRademacher/routing-comparison/blob/master/happstack-test/src/Main.hs)
- [Scotty](https://github.com/AndrewRademacher/routing-comparison/blob/master/scotty-test/src/Main.hs)
- [Snap](https://github.com/AndrewRademacher/routing-comparison/blob/master/snap-test/src/Main.hs)
- [Yesod](https://github.com/AndrewRademacher/routing-comparison/blob/master/yesod-test/src/Main.hs)
### Observations
- Happstack was the most concise (39 lines total).  This could actually be 2 lines shorter if you were using the ScopedTypeVariables language option.
- Yesod's use of TemplateHaskell did not make it more concise to use.
- Yesod's use of TemplateHaskell made it impossible to Overload a route with multiple handlers each taking different inputs.
- Yesod didn't have a canonical implementation of query parameters.
- Snap didn't support overloading a route with multiple handlers.  If a handler failed the request was rejected, it was not passed off for another handler to try.
- Snap doesn't have any type limitations, if data of the wrong type gets into the handler exceptions occur.
- Scotty, while not actually type-safe, will handle improperly typed data in the form of fail-over.  Overloading routes by type is possible.
- Scotty handles optional search parameters strangely.  If a search parameter is missing, calling for it produces an exception instead of a Maybe.

Overall, I'm a huge fan of Happstack's view of routing and they are the target to beat.  The other two frameworks both have problematic routing patterns which I believe Scotty already beats.
### Possible Pattern

``` haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}

import           Web.Scotty
import           Control.Monad.Trans
import           Data.Time
import           Data.Text.Lazy         as LT

main :: IO ()
main = scotty 3000 $ do
    get "/" getHome
    get "/time" getTime
    get "/add/?/?" [getAddNum, getAddText]
    get "/search" getSearch

getHome :: ActionM ()
getHome = html "<h1>Hello World!</h1>"

getTime :: ActionM ()
getTime = do
        t <- lift $ getCurrentTime
        html $ LT.pack $ show t

getAddNum :: Integer -> Integer -> ActionM ()
getAddNum n1 n2 = html $ LT.pack $ show (n1 + n2)

getAddText (w1::Text) (w2::Text) = html $ LT.concat [w1, w2]

getSearch :: ActionM ()
getSearch = do
        contact <- (param "contactId") `rescue` (\x -> return "Not Found")
        company <- (param "companyId") `rescue` (\x -> return "Not Found")
        html $ LT.concat [ "<ul>"
                         , "<li>Contact ID: ", (contact::Text), "</li>"
                         , "<li>Company ID: ", (company::Text), "</li>"
                         , "</ul>"
                         ]
```

This is my first thought on a possible pattern for Scotty's routing.  This would remove the need to call param inside a handler's Monad for path parameters.  It would preserve the ability to overload a route by types.  It would also not conflict with the current routing pattern in Scotty, so it should be possible to keep backwards compatibility.

I haven't yet worked out how to implement this pattern, I'm hoping to get feedback about interest in this pattern before doing the hard part.

**Comment by ocramz** [comment]
> Scotty handles optional search parameters strangely. If a search parameter is missing, calling for it produces an exception instead of a Maybe.

We have solved this since 0.21 https://hackage.haskell.org/package/scotty-0.21/changelog (it took only 10 years!) by introducing `pathParamMaybe` and friends.
Additionally, `ActionT` has now a `MonadUnliftIO`instance so we can both throw and catch exceptions inside it in a principled way.
