### ISSUE TITLE
wai-eventsource integration

### ISSUE THREAD

**Issue by pxqr** [scotty-web/scotty#80]
The problem I've encountered is that it's impossible to turn a wai `Application` into `ActionT`. Examples when we might need this includes both `wai-eventsource` and `wai-websockets` enabled applications, but lets consider the first one for a moment:

``` haskell
get "/:foo/updates" $ do 
  application (eventSourceAppChan myEventStream)
```

where `application` function is impossible to implement because `ScottyResponse` do not allow to return a plain old wai `Response`. The workaround is to set middleware with interceptor routing, which is pretty awkward.

**Comment by bsima** [comment]
> What's the status on that? I wrote a simple handler to test how that could be done:
> 
> ```
> sse :: T.Text -> ActionM ()
> sse t = do
>      setCorsHeader
>      setHeader "Content-Type" "text/event-stream"
>      setHeader "Cache-Control" "no-cache"
>      setHeader "Connection" "keep-alive"
>      raw $ encodeUtf8 t
> ```
> 
> And it works, but drops the connection nevertheless.

Why does this drop the connection despite having the keep-alive header?

**Comment by ocramz** [comment]
Well, now (since https://github.com/scotty-web/scotty/pull/233) you can have `nested` wai Applications under a Scotty route!
