### ISSUE TITLE
Param Lists/Maps

### ISSUE THREAD

**Issue by agrafix** [scotty-web/scotty#90]
PHP and other languages support sending Lists via GET and POST using the Syntax

```
param[]=a&param[]=b&param[]=c
```

You could also implement sending Maps:

```
param[key1]=val1&param[key2]=val2
```

Scotty would get two new functions

```
paramAsMap :: Parsable p => Text -> Action (Map Text p)
paramAsList :: Parsable p => Text -> Action [p]
```

**Comment by I3ck** [comment]
Could this be added to the docs somewhere? Or param be changed to actually create a list when there's an array of values for that name (or offer another function)
